### ISSUE TITLE
Jar contains js code from shadow-cljs from `resources/public` directory

### ISSUE THREAD

**Issue by geodrome** [wilkerlucio/wsscode-async#11] opened 2020-11-24 08:21 UTC
I'm trying to reduce the size of my jar and I noticed that the`[com.wsscode/async "1.0.12"]` jar contains js code from shadow-cljs in `resources` directory. Doesn't seem like it should be there. It takes up ~76M and looks like this:

public
└── js
    └── test
        ├── index.html
        └── js
            ├── cljs-runtime
            ├── manifest.edn
            └── test.js

Same is true of of `[com.wsscode/pathom "2.3.0-alpha17"]`

I'll try to use various `exclude` type options in various jar builders, but it seems like it should be addressed at the root.

**Comment by wilkerlucio** [comment] 2020-11-24 13:06
Hello, thanks for reaching, but I can't reproduce, when I look here I see the jar with 2.7MB
<img width="882" alt="Screen Shot 2020-11-24 at 10 06 17" src="https://user-images.githubusercontent.com/25736/100098358-b4226300-2e3c-11eb-8f99-b87324476bca.png">

How are you getting to this number?

**Comment by geodrome** [comment] 2020-11-24 13:40
I mean if you unzip the jar you'll find js code inside /public. I get the same size compressed.

**Comment by wilkerlucio** [comment] 2020-11-24 20:13
Gotcha, thanks for the report, fixed on `1.0.13`

**Closed as completed by wilkerlucio** 2020-11-24 20:13 UTC
